[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.24"
build_info = true
extra_output = ["storageLayout"]
ffi = true
ast = true
gas_reports = ["*"]


fs_permissions = [{ access = "read-write", path = "./" },
{ access = "read-write", path = "./script/utils/deployedContracts.json" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
