name: Solidity Contracts tests

# on:
#   pull_request:
#     branches:
#       - "**"

on:
  workflow_call:

env:
  FOUNDRY_PROFILE: ci

defaults:
  run:
    working-directory: /

jobs:
  check:
    strategy:
      fail-fast: true

    name: Twine Solidity Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Slither Security Analysis
        run: |
          pip install slither-analyzer
          slither src/
      
      - name: Run Solhint Linter
        run: |
          npm install -g solhint
          solhint 'src/**/*.sol'

      - name: Run Forge build
        run: |
          forge --version
          forge remappings
          ./script/updateSp1Version.sh
        id: build

      - name: Run Forge tests
        run: |
          forge clean
          forge test -vvv
        id: test
